language: python
python:
- '3.6'
install:
- pip install xml2rfc
script:
- xml2rfc --html draft-ytti-v6ops-flow-label.xml
- xml2rfc --text draft-ytti-v6ops-flow-label.xml
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$FLOW_LABEL_GH_PAGES_TOKEN"
  keep-history: true
  on:
    branch: master
env:
  global:
    secure: blQ6AgPOBD5qLhpw+QVKu/Zl5AHBXMF0R3sF8eXysjWv9ezQvEa9pht2EepRKArhkdf4xeAgM++8MNGGLFG2hpF2r5n7XzCVU0KImHA+YaH2/KIyLqV0eLNaUnsheiQTRcjHeaKHxtoaM43kfBS1aIx9W94UAGVMYH/KrcWTpRiVsWyKW6rSU6nweIewp+LhSlaFP03cBGvotcEcU74Db49yaRpI+sHvTfzgMBNsQhHJ78pAV8HzGrqX3lMftsCCaiyWyxokElo5UpmnpoZQU5uRN3Mt0uCzwAFDpV9TQFYXL1E2ZyzGduG9T+R013inmFyzuLt6GvdvKEjxzRC+aK0b6A759f5fiGNnztXA1J7g1srTGf9tURHHWdSYuCD9LDH73sYWknZozQHxXDyGyZ72UkhUgJEdTsCd+KAnZJ6pPeyIg4ku+ABo3JCc9BR+LmnLXuFuhb54fBVly/esA3YWiljLM1gwn67ZjQ3ZrNnPwATFHteVz5ZXgNkDHrJunRh30EHwxZxVIDLPOCOlbaHjdoHRU8euuy3MKK16DO8hiIK9goB78p4NgWE2USMLdVQBfHBe0xK4esQYZr5T4JE5IXkqAcJ9TzT4gaXTQK01RDGaaxS3Nw91q9hNFl9YYdw7nGPCiRN8SiWyGMt6XHECNygS1wlG8Y/z4RRpTF0=
